
						 
#include <a_samp>
#include <Streamer>

#define COLOR_BLANCO  (0xFFFFFFFF)
#define COLOR_NEGRO   (0x000000FF)
#define COLOR_ROJO    (0xF60000FF)
#define COLOR_AZUL    (0x0000F6FF)
#define COLOR_AZULC   (0x005BF6FF)
#define COLOR_VERDE   (0x00F600FF)
#define COLOR_VERDEC  (0x008C00FF)
#define COLOR_MORADO  (0xB505A5FF)
#define COLOR_CELESTE (0x00D5F6FF)
#define COLOR_GRIS    (0xAFAFAFFF)
#define COLOR_AMARI   (0xF6F600FF)
#define COLOR_ROJON   (0x9F0000FF)
#define COLOR_MORA    (0x0000F662)
#define COLOR_MORAN   (0x0000F6A1)
#define COLOR_MENTA   (0x00EB0062)
#define COLOR_ROSA    (0xC82AF675)
#define COLOR_AMARIL  (0xF6F653A9)
#define COLOR_ORO     (0xFFCD00FF)
#define COLOR_BRONCE  (0xC45E22F6)
#define COLOR_PLATA   (0x0000004E)
#define COLOR_PURPURA (0xB400F6F6)
#define PLAYERS_COLOR (0xFEFEFEFF)
#define PLAYERS_COLOR_VIP (0xFFA97FFF)
#define COLOR_DUDAS                     	0x93A6FFFF
#define COLOR_CHEATS_REPORTES				0xFF4600FF
#define COLOR_RADIO							0x0069FFFF
#define COLOR_DE_TRANSMISION                0x00FFB4FF
#define COLOR_DE_NARRACION 	                0xFF8200FF
#define COLOR_FAMILY						0x00EBFFFF
#define COLOR_3DLABEL_PISTAS				0xFFC800FF
#define COLOR_DM       						0xFF0055FF
#define COLOR_DM_TEAM  						0x0087FFFF
#define COLOR_OWNED_CHAT                    0x93A6FFFF
#define COLOR_PURPLE                        0xACC97F22A
#define COLOR_MENSAJES_DE_AVISOS 			0x8C8C8CFF
#define COLOR_MALETERO_ARMARIO_CAJA_FUERTE  0xC3FF00FF
#define	COLOR_KICK_JAIL_BAN                 0xFFBE00FF
#define COLOR_DE_WISPEO                     0xF5FF00FF
#define COLOR_INFO_MOVIL                    0xFFF000FF
#define COLOR_COLGAR_DESCOLGAR              0x828282FF
